//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompId { get; set; }
        public byte[] CompImg { get; set; }
        public string CompName { get; set; }
        public string CompRep { get; set; }
        public Nullable<System.DateTime> CompDOE { get; set; }
        public string CompAddr { get; set; }
        public string CompCat { get; set; }
        public string CompEmail { get; set; }
        public string CompCont { get; set; }
        public string CompDesc { get; set; }
    }
}
